import { Inter, Syne } from "next/font/google";
import Navbar from "../Navbar/Navbar";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
const syne = Syne({
  subsets: ["latin"],
  variable: "--font-syne",
});

const Layout = ({ children }: { children: React.ReactNode }) => {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${syne.variable} ${inter.variable} flex min-h-screen flex-col font-sans text-secondary`}
      >
        <Navbar />
        <main className="mt-16 flex flex-1 flex-col">{children}</main>
      </div>
    </>
  );
};

export default Layout;
