import { Inter, Syne } from "next/font/google";
import Navbar from "./Navbar";
import Head from "next/head";
import { signIn, signOut, useSession } from "next-auth/react";
import { useEffect } from "react";
import { api } from "~/utils/api";
import Loading from "./utils/Loading";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
const syne = Syne({
  subsets: ["latin"],
  variable: "--font-syne",
});

const Layout = ({ children }: { children: React.ReactNode }) => {
  const {
    data: sessionData,
    status: sessionStatus,
    update: updateSession,
  } = useSession();

  return (
    <>
      <Head>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${syne.variable} ${inter.variable} flex min-h-screen flex-col font-sans text-secondary`}
      >
        <Navbar />
        <main className="mt-16 flex flex-1 flex-col">
          {sessionStatus === "loading" ? <Loading /> : children}
        </main>
      </div>
    </>
  );
};

export default Layout;
